export const colors = {
  bg: '#f8f6ff',
  bgSurface: '#ffffff',
  bgHover: '#f0edff',
  bgElevated: '#f5f0ff',
  bgCanvas: '#f6f3ff',
  border: '#e2ddf5',
  text: '#2d2b3d',
  textMuted: '#8b85a6',
  textSubtle: '#665f85',
  accent: '#7c5cfc',
  accentHover: '#6a47f0',
  accentSoft: '#efe8ff',
  userBubble: '#7c5cfc',
  assistantBubble: '#ffffff',
  danger: '#f0466a',
  success: '#2cc985',
  white: '#ffffff',
};

export const studioStyles = {
  root: {
    display: 'flex',
    height: '100vh',
    width: '100vw',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    fontSize: '14px',
    color: colors.text,
    background: colors.bg,
    overflow: 'hidden',
  },
  // Left pane
  leftPane: {
    width: '420px',
    minWidth: '420px',
    display: 'flex',
    flexDirection: 'column' as const,
    borderRight: `1px solid ${colors.border}`,
    background: colors.bgCanvas,
  },
  topBar: {
    padding: '14px 16px',
    borderBottom: `1px solid ${colors.border}`,
    background: colors.bgSurface,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  brandLockup: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  brandMark: {
    width: '36px',
    height: '36px',
    borderRadius: '11px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: `linear-gradient(135deg, ${colors.accent} 0%, ${colors.accentHover} 100%)`,
    color: colors.white,
    fontSize: '18px',
    fontWeight: '800' as const,
    letterSpacing: '-0.04em',
    boxShadow: '0 10px 24px rgba(124, 92, 252, 0.24)',
  },
  brandText: {
    display: 'flex',
    flexDirection: 'column' as const,
    minWidth: 0,
  },
  brandName: {
    fontSize: '15px',
    fontWeight: '800' as const,
    lineHeight: '1.1',
    color: colors.text,
    letterSpacing: '-0.03em',
  },
  brandSubtle: {
    fontSize: '11px',
    color: colors.textMuted,
    lineHeight: '1.2',
  },
  iconBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    border: `1px solid ${colors.border}`,
    background: colors.bgSurface,
    color: colors.textSubtle,
    cursor: 'pointer',
    fontSize: '16px',
  },
  segmentGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
    flex: '1 1 180px',
  },
  segmentLabel: {
    fontSize: '11px',
    fontWeight: '700' as const,
    color: colors.textMuted,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
  },
  segmentedControl: {
    display: 'inline-flex',
    padding: '4px',
    borderRadius: '12px',
    background: 'rgba(255, 255, 255, 0.72)',
    border: `1px solid ${colors.border}`,
    gap: '4px',
  },
  segmentBtn: {
    padding: '8px 12px',
    borderRadius: '9px',
    border: 'none',
    background: 'transparent',
    color: colors.textSubtle,
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '700' as const,
    transition: 'background 0.15s, color 0.15s, box-shadow 0.15s',
  },
  segmentBtnActive: {
    padding: '8px 12px',
    borderRadius: '9px',
    border: 'none',
    background: colors.accent,
    color: colors.white,
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: '700' as const,
    boxShadow: '0 6px 18px rgba(124, 92, 252, 0.24)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    borderBottom: `1px solid ${colors.border}`,
    background: colors.bgSurface,
  },
  sectionTitle: {
    fontSize: '13px',
    fontWeight: '700' as const,
    color: colors.textSubtle,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
  },
  logo: {
    fontSize: '16px',
    fontWeight: '700' as const,
    color: colors.accent,
    letterSpacing: '-0.3px',
  },
  headerActions: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  btn: {
    padding: '6px 12px',
    borderRadius: '6px',
    border: `1px solid ${colors.border}`,
    background: colors.bgHover,
    color: colors.text,
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500' as const,
    transition: 'background 0.15s',
  },
  btnAccent: {
    padding: '6px 12px',
    borderRadius: '6px',
    border: 'none',
    background: colors.accent,
    color: colors.white,
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500' as const,
  },
  btnDanger: {
    padding: '4px 8px',
    borderRadius: '4px',
    border: 'none',
    background: 'transparent',
    color: colors.textMuted,
    cursor: 'pointer',
    fontSize: '12px',
  },
  // Sessions list
  sessionsList: {
    flex: '1',
    overflowY: 'auto' as const,
    padding: '12px',
  },
  setupCard: {
    margin: '12px 12px 0',
    padding: '14px',
    borderRadius: '14px',
    border: `1px solid ${colors.border}`,
    background: colors.bgSurface,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '10px',
    boxShadow: '0 10px 24px rgba(45, 43, 61, 0.04)',
  },
  setupCardTitle: {
    fontSize: '14px',
    fontWeight: '700' as const,
    color: colors.text,
  },
  setupCardDescription: {
    fontSize: '12px',
    lineHeight: '1.5',
    color: colors.textSubtle,
  },
  sessionItem: {
    padding: '12px',
    borderRadius: '12px',
    border: `1px solid ${colors.border}`,
    marginBottom: '8px',
    cursor: 'pointer',
    background: colors.bgSurface,
    transition: 'background 0.15s, transform 0.15s',
    boxShadow: '0 8px 20px rgba(45, 43, 61, 0.03)',
  },
  sessionItemTitle: {
    fontSize: '13px',
    fontWeight: '600' as const,
    color: colors.text,
    marginBottom: '4px',
  },
  sessionItemMeta: {
    fontSize: '12px',
    color: colors.textMuted,
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px',
    color: colors.textMuted,
    textAlign: 'center' as const,
    gap: '12px',
    flex: '1',
  },
  // Chat area
  chatArea: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  chatHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    borderBottom: `1px solid ${colors.border}`,
    background: colors.bgSurface,
  },
  backBtn: {
    padding: '4px 8px',
    borderRadius: '4px',
    border: `1px solid ${colors.border}`,
    background: 'transparent',
    color: colors.textMuted,
    cursor: 'pointer',
    fontSize: '13px',
  },
  messages: {
    flex: '1',
    overflowY: 'auto' as const,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  userMsg: {
    alignSelf: 'flex-end' as const,
    maxWidth: '85%',
    padding: '10px 14px',
    borderRadius: '12px 12px 2px 12px',
    background: colors.userBubble,
    color: colors.white,
    fontSize: '13px',
    lineHeight: '1.5',
  },
  assistantMsg: {
    alignSelf: 'flex-start' as const,
    maxWidth: '85%',
    padding: '10px 14px',
    borderRadius: '12px 12px 12px 2px',
    background: colors.assistantBubble,
    border: `1px solid ${colors.border}`,
    color: colors.text,
    fontSize: '13px',
    lineHeight: '1.5',
    whiteSpace: 'pre-wrap' as const,
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  msgContext: {
    fontSize: '11px',
    color: colors.accent,
    marginBottom: '4px',
    padding: '4px 8px',
    background: 'rgba(124, 92, 252, 0.1)',
    borderRadius: '4px',
    display: 'inline-block',
  },
  msgPatches: {
    marginTop: '8px',
    fontSize: '11px',
    color: colors.textMuted,
  },
  msgRevert: {
    marginTop: '6px',
    padding: '3px 8px',
    borderRadius: '4px',
    border: `1px solid ${colors.border}`,
    background: 'transparent',
    color: colors.textMuted,
    cursor: 'pointer',
    fontSize: '11px',
  },
  // Selected element badge
  selectedBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    margin: '0 16px',
    background: 'rgba(124, 92, 252, 0.08)',
    border: `1px solid ${colors.accent}`,
    borderRadius: '8px',
    fontSize: '12px',
    color: colors.accent,
  },
  lockedNotice: {
    margin: '0 16px 12px',
    padding: '14px',
    borderRadius: '12px',
    border: `1px solid ${colors.border}`,
    background: colors.bgSurface,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  lockedNoticeTitle: {
    fontSize: '13px',
    fontWeight: '700' as const,
    color: colors.text,
  },
  lockedNoticeDescription: {
    fontSize: '12px',
    lineHeight: '1.5',
    color: colors.textSubtle,
  },
  // Input area
  inputArea: {
    padding: '12px 16px',
    borderTop: `1px solid ${colors.border}`,
    display: 'flex',
    gap: '8px',
    background: colors.bgSurface,
    position: 'relative' as const,
    alignItems: 'flex-end',
  },
  modeIconBtn: {
    padding: '8px 12px',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    background: colors.bgSurface,
    color: colors.textMuted,
    cursor: 'pointer',
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeIconBtnActive: {
    padding: '8px 12px',
    borderRadius: '8px',
    border: `1px solid ${colors.accent}`,
    background: colors.accentSoft,
    color: colors.accent,
    cursor: 'pointer',
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoWrap: {
    position: 'relative' as const,
    alignSelf: 'flex-end' as const,
  },
  modeInfoBtn: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    background: colors.bgSurface,
    color: colors.textSubtle,
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '700' as const,
  },
  modeInfoPopover: {
    position: 'absolute' as const,
    right: '0',
    bottom: '46px',
    width: '220px',
    padding: '12px',
    borderRadius: '12px',
    border: `1px solid ${colors.border}`,
    background: colors.bgSurface,
    boxShadow: '0 16px 32px rgba(45, 43, 61, 0.14)',
    zIndex: 20,
  },
  modeInfoPopoverTitle: {
    fontSize: '12px',
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: '6px',
  },
  modeInfoPopoverBody: {
    fontSize: '12px',
    lineHeight: '1.5',
    color: colors.textSubtle,
  },
  input: {
    flex: '1',
    padding: '10px 14px',
    borderRadius: '8px',
    border: `1px solid ${colors.border}`,
    background: colors.bg,
    color: colors.text,
    fontSize: '13px',
    outline: 'none',
    resize: 'none' as const,
    lineHeight: '1.4',
    minHeight: '20px',
    maxHeight: '120px',
  },
  sendBtn: {
    padding: '8px 16px',
    borderRadius: '8px',
    border: 'none',
    background: colors.accent,
    color: colors.white,
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '600' as const,
    alignSelf: 'flex-end' as const,
  },
  // Right pane
  rightPane: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column' as const,
    background: colors.bg,
  },
  previewHero: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    padding: '18px 20px',
    borderBottom: `1px solid ${colors.border}`,
    background: `linear-gradient(135deg, ${colors.bgSurface} 0%, ${colors.accentSoft} 100%)`,
  },
  previewHeroCopy: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  previewHeroTitle: {
    fontSize: '20px',
    fontWeight: '800' as const,
    lineHeight: '1.1',
    color: colors.text,
    letterSpacing: '-0.04em',
  },
  previewHeroDescription: {
    fontSize: '12px',
    lineHeight: '1.5',
    color: colors.textSubtle,
    maxWidth: '480px',
  },
  previewHeroBtn: {
    padding: '14px 20px',
    borderRadius: '14px',
    border: 'none',
    background: colors.accent,
    color: colors.white,
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: '800' as const,
    boxShadow: '0 18px 32px rgba(124, 92, 252, 0.22)',
    whiteSpace: 'nowrap' as const,
  },
  previewHeroBtnActive: {
    padding: '14px 20px',
    borderRadius: '14px',
    border: `1px solid ${colors.accent}`,
    background: colors.bgSurface,
    color: colors.accent,
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: '800' as const,
    boxShadow: '0 18px 32px rgba(124, 92, 252, 0.12)',
    whiteSpace: 'nowrap' as const,
  },
  previewBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    borderBottom: `1px solid ${colors.border}`,
    background: colors.bgSurface,
  },
  urlInput: {
    flex: '1',
    padding: '6px 12px',
    borderRadius: '6px',
    border: `1px solid ${colors.border}`,
    background: colors.bg,
    color: colors.text,
    fontSize: '13px',
    outline: 'none',
    fontFamily: 'monospace',
  },
  iframe: {
    flex: '1',
    border: 'none',
    background: colors.white,
  },
  // Component selector overlay on iframe
  selectorOverlay: {
    position: 'absolute' as const,
    inset: '0',
    cursor: 'crosshair',
    zIndex: 10,
    pointerEvents: 'none' as const,
  },
  // Error
  error: {
    padding: '8px 12px',
    margin: '8px 16px',
    background: 'rgba(229, 57, 53, 0.1)',
    border: `1px solid ${colors.danger}`,
    borderRadius: '6px',
    fontSize: '12px',
    color: colors.danger,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  // Loading
  loading: {
    alignSelf: 'flex-start' as const,
    padding: '10px 14px',
    color: colors.textMuted,
    fontSize: '13px',
  },
  // PR Dialog
  dialogOverlay: {
    position: 'fixed' as const,
    inset: '0',
    background: 'rgba(44,43,61,0.4)',
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialog: {
    background: colors.bgSurface,
    borderRadius: '16px',
    padding: '24px',
    width: '440px',
    border: `1px solid ${colors.border}`,
    boxShadow: '0 8px 32px rgba(124,92,252,0.12)',
  },
  dialogTitle: {
    fontSize: '18px',
    fontWeight: '600' as const,
    color: colors.text,
    marginBottom: '10px',
  },
  dialogDescription: {
    fontSize: '13px',
    lineHeight: '1.5',
    color: colors.textSubtle,
    marginBottom: '18px',
  },
  dialogField: {
    marginBottom: '14px',
  },
  dialogLabel: {
    display: 'block',
    fontSize: '12px',
    fontWeight: '600' as const,
    color: colors.textMuted,
    marginBottom: '6px',
  },
  dialogInput: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: '6px',
    border: `1px solid ${colors.border}`,
    background: colors.bg,
    color: colors.text,
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  dialogHelp: {
    fontSize: '12px',
    lineHeight: '1.5',
    color: colors.textMuted,
    marginTop: '6px',
  },
  dialogTextarea: {
    width: '100%',
    padding: '8px 12px',
    borderRadius: '6px',
    border: `1px solid ${colors.border}`,
    background: colors.bg,
    color: colors.text,
    fontSize: '14px',
    outline: 'none',
    minHeight: '80px',
    resize: 'vertical' as const,
    boxSizing: 'border-box' as const,
  },
  dialogActions: {
    display: 'flex',
    gap: '8px',
    justifyContent: 'flex-end',
    marginTop: '20px',
  },
};
